/*
Pull Request Pipeline:
This pipeline is triggered whenever someone makes a pull request to the main branch. 
It checks out the code, builds Docker images, runs tests, and sends status updates to GitHub.
*/
pipeline {
    agent any
    tools {
        gradle 'Gradle-8.5'
        dockerTool 'Docker-latest'
        nodejs 'NodeJS-21.6.1'
    }
    
    stages {
        stage('Checkout') {
            steps {
                script {
                    checkout scm
                }
            }
        }

        stage('Build Java Spring Server' ) {
            steps {
                echo 'Build JAR file of Java Spring server'
                withGradle {
                    sh 'cd ./backend/hello-world-server/ && gradle build'
                }
            }
        }
        
        stage('Test Java Spring Server' ) {
            steps { 
                echo 'Run tests for Java Spring server'                
                withGradle {                    
                    sh 'cd ./backend/hello-world-server/ && gradle test'
                }
            }
        }

        stage('Install NodeJS depedencies') {
            steps {
                echo 'Install NodeJS depedencies'
                withNodeJS {
                    sh 'npm install'
                }
            }     
        }

        stage('Test React Client') {
            steps {
                echo 'Test React client'
                withNodeJS {
                    sh 'npm test'
                }
            }
        }
    }
}