version: '3'

services:

  jenkins:
    build: .
    container_name: hello-world-jenkins
    privileged: true
    restart: always
    ports:
      - 8090:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker

  registry:
    image: registry
    container_name: hello-world-registry
    restart: always
    ports:
      - 5010:5010