apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-pod
  template:
    metadata:
      labels:
        app: react-pod
    spec:
      containers:
      - name: react-pod
        image: localhost:5010/react-client:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP